command('external-images pull'):
  env:
    EXTERNAL_REGISTRIES: = json_encode(@('docker.external_image_registries'))
  exec: |
    #!php
    foreach (json_decode($env['EXTERNAL_REGISTRIES'], true) as $registry) {
      $pass = escapeshellarg($registry['password']);
      $user = escapeshellarg($registry['username']);
      $url = escapeshellarg($registry['url']);
      $command = "docker login --username=$user --password-stdin $url";
      echo $command . PHP_EOL;
      passthru("echo $pass | $command");
    }

    var_dump($_ENV);
    exit;
    $confArgs = [];
    if (strlen(@$env['CI']) > 0 || strlen(@$env['BUILD_ID']) > 0) {
      $confArgs[] = "--skip-exists";
    }
    $confArgs = join(' ', array_map('escapeshellarg', $confArgs));

    $command = "ws external-images config $confArgs | docker-compose -f - pull";
    echo $command . PHP_EOL;
    passthru($command);

    foreach (json_decode($env['EXTERNAL_REGISTRIES'], true) as $registry) {
      $url = escapeshellarg($registry['url']);
      $command = "docker logout $url";
      echo $command . PHP_EOL;
      passthru($command);
    }
